name: test

on:
  push: {}

jobs:
  test-and-build:
    defaults:
      run:
        shell: bash

    container:
      image: ghcr.io/luzifer-docker/action-env:master@sha256:06e2043d1dbc866ed1700fe2f3404eeca61bd9c3a41cf5aab6ce9f2ae1cc88e1
      env:
        CGO_ENABLED: 0
        GOPATH: /go

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Marking workdir safe
        run: git config --global --add safe.directory /__w/go-openssl/go-openssl

      - name: Lint and test code
        run: make lint test

      - name: Record benchmark
        run: make benchmark

      - name: Execute Trivy scan
        run: make trivy
